# Parameters for training a BarlowTrack model

# CHANGEME: these parameters are specific for each model and dataset
project_path: "/lisc/scratch/neurobiology/zimmer/fieseler/wbfm_projects_future/barlow_tests/ZIM2165_Gcamp7b_worm1-2022_11_28/project_config.yaml"

# Optional (but recommended) path to a pretrained model; note that the architecture parameters must be the same for this to work
# If you want to train from scratch, set this to null
pretrained_model_path: /lisc/scratch/neurobiology/zimmer/wbfm/TrainedBarlow/barlow_ZIM2165_Gcamp7b_worm1-2022_11_28_from_search/trial_13/resnet50.pth  # Directly pass the .pth file of the pretrained model (the model weights)

# Optional (but recommended): if you have a wandb account, you can set the project name and run name here
wandb_name: null      # Project name
wandb_username: null  # Account name

####
# Hyperparameters for training the model
####

# Architecture
projector: '2048-2048'  # Original paper argued that larger final size is better
projector_final: 2048
embedding_dim: 128  # Projector also gets an additional first layer of size 'embedding_dim'

backbone_kwargs:
  num_levels: 2
  f_maps: 4  # Default in paper is 64... is this super small?

# Size of image crop (around each neuron) to use
target_sz_z: 4
target_sz_xy: 128

# Augmentation hyperparameters
# First path through the Siamese network
p_RandomAffine_base: 1.0
p_RandomBlur_base: 0.1
p_RandomNoise_base: 0.5

# Second path; default is more augmentation
p_RandomAffine_flip: 0  # A 180 degree rotation, like a flip
p_RandomBlur: 0.0
p_RandomAffine: 0.1  # At least one deformation should have probability 1, so that the two images are definitely different
p_RandomElasticDeformation: 0.0
zxy_RandomElasticDeformation: [1, 3, 3]
p_RandomNoise: 0.1
std_RandomNoise: 0.25

# Optimization hyperparameters
lambd: 0.0051
batch_size: 1  # This should stay; one volume = one batch
weight_decay: 1e-6
epochs: 50
lr: 0.0001

num_frames: 200
train_fraction: 0.8
val_fraction: 0.1

# Hyperparameters for the new (transposed) BarlowTrack loss
lambd_obj: 0.67  # Set to 0 to not use the transposed loss

# Debugging and logging parameters
print_freq: 100
rank: 0
dryrun: false
DEBUG: false
