# Parameters for training a BarlowTrack model

# CHANGEME: these parameters are specific for each model and dataset
project_path: "/lisc/scratch/neurobiology/zimmer/fieseler/wbfm_projects_future/barlow_tests/ZIM2165_Gcamp7b_worm1-2022_11_28/project_config.yaml"
dryrun: false
DEBUG: false

# Optional (but recommended) path to a pretrained model
# If you want to train from scratch, set this to null
pretrained_model_path: null

# Optional (but recommended): if you have a wandb account, you can set the project name and run name here
wandb_name: null      # Project name
wandb_username: null  # Account name

# Hyperparameters for training the model; do not change these unless you know what you're doing
projector: '2048-2048-256'
embedding_dim: 2048
lambd: 0.0051
batch_size: 1
weight_decay: 1e-6
epochs: 50
print_freq: 100
rank: 0
lr: 0.0001
learning_rate_weights: 0.2
learning_rate_biases: 0.0048
target_sz:
  - 4
  - 128
  - 128
num_frames: 200
train_fraction: 0.8
val_fraction: 0.1

# Hyperparameters for the new (transposed) BarlowTrack loss
lambd_obj: 0.67
train_both_correlations: true
